import { PredefinedHostMeta } from './types';

export const DEFAULT_HOSTS: PredefinedHostMeta[] = [
  {
    id: 'disable-apps',
    name: '_disable_apps',
    description: 'Disable certain Apps',
    host: ['*://*.crunchyroll.com/*', '*://music.youtube.com/*'],
    auto: false,
    allFrames: false,
    disabled: true,
  },
  {
    id: 'trigger-parser',
    name: '_trigger_parser_',
    description: 'Trigger Parser',
    host: '<all_urls>',
    auto: false,
    allFrames: false,
    parse: 'body',
  },
  {
    id: 'kochounoyume-cde-parser',
    name: 'CDE Parser',
    description: 'Parses dictionary entries for the JPDB CDE user script',
    host: [
      '*://jpdb.io/vocabulary/*',
      '*://jpdb.io/review*',
      '*://jpdb.io/deck*',
      '*://jpdb.io/search*',
    ],
    auto: true,
    optOut: true,
    allFrames: false,
    parserClass: 'kochounoyume-parser',
    filter: '.meaning-subsection-label',
    addedObserver: {
      notifyFor: '.custom-dictionary-entry',
      checkNested: '.result.vocabulary',
    },
  },
  {
    id: 'luna-translator-parser',
    name: 'Luna Translator Parser',
    description: 'Parse lunatranslator span content from local HTML file',
    host: ['file:///*LunaTranslator*mainui.html', 'file:///*LunaTranslator*transhist.html'],
    auto: true,
    optOut: true,
    allFrames: false,
    parseVisibleObserver: true,
    parserClass: 'luna-translator-parser',
    addedObserver: {
      notifyFor: '.lunatranslator_clickword, .lunatranslator_text_all, .origin',
      observeFrom: 'body',
      config: {
        childList: true,
        subtree: true,
      },
    },
  },
  {
    id: 'texthooker-parser',
    name: 'Texthooker Parser',
    description: 'Parse hooked texts (anacreondjt, renji-xd and learnjapanese.moe)',
    host: [
      '*://anacreondjt.gitlab.io/texthooker.html',
      '*://learnjapanese.moe/texthooker.html',
      '*://renji-xd.github.io/texthooker-ui/',
      '*://*/texthooker$',
    ],
    auto: true,
    optOut: true,
    allFrames: false,
    parseVisibleObserver: true,
    parserClass: 'texthooker-parser',
    addedObserver: {
      notifyFor: '.textline, .line_box, .my-2.cursor-pointer, p',
      observeFrom: ['#textlog, main', 'body'],
    },
  },
  {
    id: 'exstatic-parser',
    name: 'ExStatic Parser',
    description: 'Enables parsing for ExStatic',
    host: '*://kamwithk.github.io/exSTATic/tracker.html',
    auto: true,
    optOut: true,
    allFrames: false,
    parseVisibleObserver: true,
    custom: 'ExStaticParser',
    addedObserver: {
      notifyFor: '.sentence-entry',
      observeFrom: '#entry_holder',
    },
  },
  {
    id: 'readwok-parser',
    name: 'Readwok Parser',
    description: 'Parses Readwok books',
    host: '*://app.readwok.com/*',
    auto: true,
    optOut: true,
    allFrames: false,
    parseVisibleObserver: true,
    custom: 'ReadwokParser',
    addedObserver: {
      notifyFor: 'div[class*="styles_paragraph_"], div[class*="styles_reader_"]',
    },
  },
  {
    id: 'ttsu-parser',
    name: 'Ttsu Parser',
    description: 'Parses Ttsu books',
    host: '*://reader.ttsu.app/*',
    auto: true,
    optOut: true,
    allFrames: false,
    custom: 'TtsuParser',
    parseVisibleObserver: true,
    addedObserver: {
      notifyFor: 'div.book-content',
    },
  },
  // {
  //   id: 'youtube-comments-parser',
  //   name: 'YouTube Comments Parser',
  //   description: 'Parses YouTube comments',
  //   host: ['*://*.youtube.com/*', '*://*.youtu.be/*'],
  //   auto: true,
  //   optOut: true,
  //   allFrames: false,
  //   parseVisibleObserver: true,
  //   parserClass: 'youtube-parser',
  //   addedObserver: {
  //     notifyFor: 'ytd-comment-view-model',
  //   },
  // },
  {
    id: 'mokuro-parser',
    name: 'Mokuro Parser',
    description: 'Parses manga on Mokuro',
    host: '*://reader.mokuro.app/*',
    auto: true,
    optOut: true,
    allFrames: true,
    custom: 'MokuroParser',
    parseVisibleObserver: true,
    addedObserver: {
      notifyFor: '#manga-panel',
    },
  },
  {
    id: 'mokuro-legacy-parser',
    name: 'Mokuro Legacy Parser',
    description: 'Parses manga on Mokuro (legacy)',
    host: 'file:///*mokuro*.html',
    auto: true,
    optOut: true,
    allFrames: true,
    custom: 'MokuroLegacyParser',
    parseVisibleObserver: true,
  },
  {
    id: 'wikipedia-parser',
    name: 'Wikipedia Parser',
    description: 'Parses Japanese Wikipedia',
    host: ['*://ja.wikipedia.org/*', '*://ja.m.wikipedia.org/*'],
    auto: true,
    optOut: true,
    allFrames: false,
    parserClass: 'wikipedia-parser',
    parseVisibleObserver: true,
    filter:
      '.p-lang-btn, .vector-menu-heading-label, .vector-toc-toggle, .vector-page-toolbar, .mw-editsection, sup.reference',
    addedObserver: {
      notifyFor: '#firstHeading, #mw-content-text .mw-parser-output > *, .mwe-popups-extract > *',
    },
  },
  {
    id: 'satori-reader-parser',
    name: 'Satori Reader Parser',
    description: 'Parses Satori Reader articles',
    host: '*://*.satorireader.com/articles/*',
    auto: true,
    optOut: true,
    allFrames: false,
    parserClass: 'satori-reader-parser',
    parse: '#article-content',
    filter: '.play-button-container, .notes-button-container, .fg, .wpr',
    custom: 'SatoriReaderParser',
  },
  {
    id: 'nhk-parser',
    name: 'NHK Parser',
    description: 'Parses NHK articles and content',
    host: [
      '*://*.nhk.or.jp/news/html/*',
      '*://*.nhk.or.jp/news/easy/*',
      '*://news.web.nhk/news/easy/*',
      '*://news.web.nhk/news/html/*',
    ],
    auto: true,
    optOut: true,
    allFrames: false,
    parserClass: 'nhk-parser',
    parseVisibleObserver: true,
    addedObserver: {
      notifyFor: '#main, #js-article-body, #js-article-date, .article-title',
    },
  },
  {
    id: 'bunpro-parser',
    name: 'Bunpro Parser',
    description: 'Parses Bunpro graded reader sections',
    host: '*://bunpro.jp/*',
    auto: true,
    optOut: true,
    allFrames: false,
    parserClass: 'bunpro-parser',
    parseVisibleObserver: true,
    addedObserver: {
      notifyFor: 'div.mx-auto',
    },
  },
  {
    id: 'asbplayer-parser',
    name: 'asbplayer Parser',
    description: 'Parses asbplayer subtitles',
    host: '<all_urls>',
    auto: true,
    optOut: true,
    allFrames: true,
    css: '.asbplayer-subtitles-container-bottom { z-index: 2147483646 }',
    parserClass: 'asb-player-parser',
    addedObserver: {
      notifyFor: '.asbplayer-offscreen',
    },
  },
  {
    id: 'aozora-parser',
    name: 'Aozora Bunko Parser',
    description: 'Parses Aozora Bunko literature',
    host: '*://*.aozora.gr.jp/*',
    auto: true,
    optOut: true,
    allFrames: false,
    parserClass: 'aozora-parser',
    custom: 'AozoraParser',
  },
];
